### ISSUE TITLE
Self-intersection on output line

### ISSUE THREAD

**Issue by VasiliosKalogirou** [albertferras/simplipy#15]
Hi Albert, 
I checked the "Repair intersections" option in the plugin but I still got a self intersection on my last line. Can you please have a look?

![wgis_150_resolve2](https://cloud.githubusercontent.com/assets/15183670/11914016/905b4bf6-a66c-11e5-92d2-e2ea33f6d7da.png)

**Comment by albertferras** [comment]
Hi Vasilios,

Would it be possible to get the geometry of the last line? (WKT , WKB or shapefile) That way I can debug and see what's going on, because that shouldn't happen.

Thank you for letting me know!

**Comment by VasiliosKalogirou** [comment]
Hi Albert,
My dataset was a shapefile. Contact me if you would like more information about it or even send you me data.
Looking forward to hearing back from you about it.

**Comment by albertferras** [comment]
It would be great if you could send me the shapefile at albertferras @ gmail.com or upload to any file sharing page (mega.co.nz, mediafire, etc..). Alternatively you could also paste the problematic geometric using this qgis plugin: https://plugins.qgis.org/plugins/getWKT/ and paste here the WKT (something like MULTILINESTRING ((10 10, 20 20, 10 40),
(40 40, 30 30, 40 20, 30 10)))

**Comment by albertferras** [comment]
Done, fix will be available when v0.50 is released
