### ISSUE TITLE
Version 0.50 causes QGIS to crash upon quiting

### ISSUE THREAD

**Issue by haojiezhu** [albertferras/simplipy#18]
Just updated SimpliPy to 0.5 today. Now QGIS crashes every time I try to quit QGIS. It happens on both Windows and Ubuntu. After I switch back to 0.4, everything is normal again. I am using QGIS 2.12.2.

**Comment by albertferras** [comment]
Thanks for raising this. I'll fix and make a hotfix release 0.5.1 to solve this asap.

**Comment by albertferras** [comment]
Fixed on version 0.51. Will be available on QGIS plugin repository when they approve the new version upload.
